-- ====================================================================
-- URBAN DISASTER RESPONSE & RESOURCE ORCHESTRATION PLATFORM (UDR-ORP)
-- FILE 02: SEQUENCES & PERFORMANCE INDEXES
-- Target: Oracle Database
-- ====================================================================

-- Clean up existing sequences
BEGIN
    FOR s IN (SELECT sequence_name FROM user_sequences WHERE sequence_name IN (
        'SEQ_ROLES', 'SEQ_USERS', 'SEQ_LOCATIONS', 'SEQ_SHELTERS', 'SEQ_WAREHOUSES',
        'SEQ_INCIDENTS', 'SEQ_REQUESTS', 'SEQ_REQUEST_ITEMS', 'SEQ_RESOURCE_TYPES',
        'SEQ_RESOURCES', 'SEQ_VEHICLES', 'SEQ_RESPONDERS', 'SEQ_SKILLS',
        'SEQ_MISSIONS', 'SEQ_INVENTORY', 'SEQ_INV_TRANS', 'SEQ_HANDOVERS',
        'SEQ_FIELD_REPORTS', 'SEQ_INCIDENT_LOGS'
    )) LOOP
        EXECUTE IMMEDIATE 'DROP SEQUENCE ' || s.sequence_name;
    END LOOP;
END;
/

-- --------------------------------------------------------------------
-- SEQUENCES FOR PRIMARY KEY GENERATION
-- --------------------------------------------------------------------
CREATE SEQUENCE SEQ_ROLES START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_USERS START WITH 1001 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_LOCATIONS START WITH 1001 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_SHELTERS START WITH 1001 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_WAREHOUSES START WITH 1001 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_INCIDENTS START WITH 1001 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_REQUESTS START WITH 1001 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_REQUEST_ITEMS START WITH 1001 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_RESOURCE_TYPES START WITH 1001 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_RESOURCES START WITH 1001 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_VEHICLES START WITH 1001 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_RESPONDERS START WITH 1001 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_SKILLS START WITH 1001 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_MISSIONS START WITH 1001 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_INVENTORY START WITH 1001 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_INV_TRANS START WITH 1001 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_HANDOVERS START WITH 1001 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_FIELD_REPORTS START WITH 1001 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_INCIDENT_LOGS START WITH 1001 INCREMENT BY 1 NOCACHE;

-- --------------------------------------------------------------------
-- PERFORMANCE & FILTER INDEXES
-- --------------------------------------------------------------------
-- Incident Filtering
CREATE INDEX IDX_INC_STATUS ON INCIDENTS(Status);
CREATE INDEX IDX_INC_SEVERITY ON INCIDENTS(Severity);
CREATE INDEX IDX_INC_LOCATION ON INCIDENTS(LocationID);
CREATE INDEX IDX_INC_STARTTIME ON INCIDENTS(StartTime);

-- Request Prioritization & Querying
CREATE INDEX IDX_REQ_STATUS ON REQUESTS(Status);
CREATE INDEX IDX_REQ_PRIORITY ON REQUESTS(Priority);
CREATE INDEX IDX_REQ_INCIDENT ON REQUESTS(IncidentID);
CREATE INDEX IDX_REQ_CREATED ON REQUESTS(CreatedAt);

-- Mission Lifecycle
CREATE INDEX IDX_MISS_STATUS ON MISSIONS(Status);
CREATE INDEX IDX_MISS_REQUEST ON MISSIONS(RequestID);
CREATE INDEX IDX_MISS_RESPONDER ON MISSIONS(ResponderID);
CREATE INDEX IDX_MISS_VEHICLE ON MISSIONS(VehicleID);

-- Resource Tracking
CREATE INDEX IDX_RES_AVAIL ON RESOURCES(AvailabilityStatus);
CREATE INDEX IDX_RES_TYPE ON RESOURCES(ResourceTypeID);
CREATE INDEX IDX_RES_PROV ON RESOURCES(ProviderID);

-- Inventory & Stock Alerts
CREATE INDEX IDX_INV_WH ON INVENTORY(WarehouseID);
CREATE INDEX IDX_INV_RESTYPE ON INVENTORY(ResourceTypeID);

-- Field Reports & Audit Logs
CREATE INDEX IDX_FR_MISSION ON FIELD_REPORTS(MissionID);
CREATE INDEX IDX_FR_TYPE ON FIELD_REPORTS(ReportType);
CREATE INDEX IDX_IL_INCIDENT ON INCIDENT_LOGS(IncidentID);
CREATE INDEX IDX_IL_TIMESTAMP ON INCIDENT_LOGS(Timestamp);

COMMIT;
